name: lfcont
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: lfcont
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
        required: false
    command: ["air", "-c", ".air.toml"]
    env_file:
      - .env
    profiles:
      - dev
      - local

  postgres:
    image: postgres
    container_name: lfcont-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - local
